creation_rules:
- path_regex: wtfis.env
  age: age1y7r3ycr37pdg69f5rjxgymxe3jt4y6rnyysjxtr42qy257j8h59q70ugvc
  key_groups: []
- path_regex: .*\\.(ya?ml|json|ini|env)
  age: age1y7r3ycr37pdg69f5rjxgymxe3jt4y6rnyysjxtr42qy257j8h59q70ugvc
  key_groups: []
onepassworditem: op://Personal/SOPS_AGE_KEY_FILE/credential
