return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "flake8",
        "gofumpt",
        "goimports",
        "gopls",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "nil",
        "nixfmt",
        "nixpkgs-fmt",
        "prettier",
        "pyright",
        "ruff",
        "shellcheck",
        "shfmt",
        "shfmt",
        "sonarlint-language-server",
        "stylua",
        "stylua",
        "swiftlint",
        "yamllint",
      },
    },
  },
}
